spring:
  config:
    activate:
      on-profile: dev

# MyBatis Plus 开发环境配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.yl.paike.teacher: DEBUG
    com.baomidou.mybatisplus: DEBUG
